# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Don't run pre-commit on files under third-party/
exclude: "^\
  (third-party/.*)\
  "
repos:
  # Automatic code formatting
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        description: Automatic code formatting.
        stages: [commit]
        exclude: \.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|src/api/api_samples/python_client/ext|internal_api_scripts|migrations|noVNC|static|static_src|setip.py
        language_version: python3.10

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--ignore=E402,F403,F401,F405,W503"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: [--profile=black]

  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v15.0.6
  #   hooks:
  #     - id: clang-format

  # - repo: https://github.com/PyCQA/pylint
  #   rev: v2.16.0b1
  #   hooks:
  #     - id: pylint
  #       args:
  #         [
  #           "--max-line-length=120",
  #           "--ignore=C0114,C0115,C0116,C0103,E0401,W0613,W0127,R0903,W0611",
  #         ]

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.20.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v0.991"
  #   hooks:
  #     - id: mypy
